// AI 코딩 에이전트 확장 디렉터리 데이터 계약.
//
// 플러그인·훅·스킬·슬래시 명령·서브에이전트·MCP 서버·워크플로우·룰셋을
// 플랫폼(Claude Code, Cursor, Copilot, Codex, Gemini CLI 등)과 도메인 카테고리로
// 세분화해 검색 가능하게 구조화한다. 국내 사용자가 바로 적용하도록 설치/사용
// 한 줄과 한국어 팁(koreanNote)을 포함한다.

export type ExtensionKind =
  | '플러그인'
  | '훅'
  | '스킬'
  | '슬래시 명령'
  | '서브에이전트'
  | 'MCP 서버'
  | '하네스'
  | '위젯'
  | '로컬 모델 UI'
  | '모델 런타임'
  | '워크플로우'
  | '룰셋/지침'
  | '템플릿'

export type ExtensionPlatform =
  | 'Claude Code'
  | 'Cursor'
  | 'GitHub Copilot'
  | 'Codex CLI'
  | 'Gemini CLI'
  | 'Windsurf'
  | '범용'

/** 도메인 카테고리 — 세분화 검색의 핵심 축. */
export type ExtensionCategory =
  | '코드 리뷰'
  | '테스트/품질'
  | '문서화'
  | 'Git/PR'
  | '보안'
  | '디자인/UI'
  | '데이터베이스'
  | '브라우저 자동화'
  | '검색/리서치'
  | '생산성'
  | '배포/DevOps'
  | '컨텍스트 관리'
  | '평가/하네스'
  | '에이전트 UI'
  | '로컬 모델'
  | '모델 서빙'

export type ExtensionMaturity = '공식' | '커뮤니티'
export type ExtensionInstallDifficulty = '쉬움' | '보통' | '고급'
export type ExtensionThumbnailRatio = 'video' | 'cover' | 'square'
export type ExtensionThumbnailFit = 'cover' | 'contain'
export type ExtensionRankGrade = 'S' | 'A' | 'B' | 'C' | '미분류'

export type AgentExtension = {
  id: string
  name: string
  kind: ExtensionKind
  platform: ExtensionPlatform
  category: ExtensionCategory
  maturity: ExtensionMaturity
  summary: string
  /** 무엇을 하는지 핵심 항목. */
  whatItDoes: string[]
  /** 설치/활성화 한 줄. */
  install: string
  /** 사용 한 줄(슬래시 명령, 설정 키 등). */
  usage: string
  koreanNote?: string
  /** 편집자가 매긴 추천 순위. 낮을수록 우선 추천. */
  rank?: number
  rankReason?: string
  installDifficulty?: ExtensionInstallDifficulty
  installSteps?: string[]
  bestFor?: string[]
  adoptionSignal?: string
  lastVerified?: string
  thumbnailUrl?: string
  thumbnailDomain?: string
  thumbnailRatio?: ExtensionThumbnailRatio
  thumbnailFit?: ExtensionThumbnailFit
  url: string
  sourceIds: string[]
  tags: string[]
}

export const agentExtensions: AgentExtension[] = [
  {
    id: 'ext-cc-plugins',
    name: 'Claude Code 플러그인 + 마켓플레이스',
    kind: '플러그인',
    platform: 'Claude Code',
    category: '생산성',
    maturity: '공식',
    summary:
      '슬래시 명령·서브에이전트·훅·MCP를 하나로 묶어 배포하는 플러그인 시스템과 마켓플레이스.',
    whatItDoes: [
      '명령/에이전트/훅/MCP를 단일 플러그인으로 패키징',
      '팀·커뮤니티 마켓플레이스에서 설치/공유',
      '프로젝트별로 활성 플러그인 구성',
    ],
    install: '/plugin marketplace add <owner/repo> 후 /plugin install <name>',
    usage: '/plugin 메뉴에서 설치·관리',
    koreanNote: '사내 표준 명령·훅을 플러그인으로 묶어 팀 전체에 배포하면 온보딩이 빨라집니다.',
    url: 'https://docs.claude.com/en/docs/claude-code/plugins',
    sourceIds: ['claude-code-docs'],
    tags: ['plugin', 'marketplace', 'claude-code', '팀'],
  },
  {
    id: 'ext-cc-hooks-format',
    name: 'PostToolUse 포맷/린트 훅',
    kind: '훅',
    platform: 'Claude Code',
    category: '테스트/품질',
    maturity: '공식',
    summary: '파일 편집 직후 자동으로 prettier/eslint를 실행해 일관된 코드 스타일을 강제하는 훅.',
    whatItDoes: [
      'Edit/Write 후 변경 파일에 포매터 실행',
      '린트 실패를 에이전트에 피드백으로 반환',
      '수동 정리 단계 제거',
    ],
    install: 'settings.json의 hooks.PostToolUse에 matcher + command 등록',
    usage: 'Edit|Write matcher → `prettier --write $FILE` 류 명령',
    koreanNote: '커밋 훅과 분리해 에이전트 편집 즉시 정리되므로 verify 게이트 실패가 줄어듭니다.',
    url: 'https://docs.claude.com/en/docs/claude-code/hooks',
    sourceIds: ['claude-code-docs'],
    tags: ['hook', 'lint', 'format', '품질'],
  },
  {
    id: 'ext-cc-secret-scan-hook',
    name: '시크릿 스캔 PostToolUse 훅',
    kind: '훅',
    platform: 'Claude Code',
    category: '보안',
    maturity: '커뮤니티',
    summary: '에이전트가 파일을 쓸 때마다 gitleaks류 스캐너로 비밀키 노출을 차단하는 훅.',
    whatItDoes: [
      '쓰기 작업마다 변경분 시크릿 스캔',
      '탐지 시 차단/경고 반환',
      '공개 레포 사고를 사전 방지',
    ],
    install: 'PostToolUse 훅에서 scan-secret 스크립트 실행',
    usage: 'Write|Edit matcher → gitleaks detect 호출',
    koreanNote: '공개 레포·이력서/포트폴리오성 저장소에 특히 유효합니다.',
    url: 'https://docs.claude.com/en/docs/claude-code/hooks',
    sourceIds: ['claude-code-docs'],
    tags: ['hook', 'security', 'secret', 'gitleaks'],
  },
  {
    id: 'ext-cc-skill-pdf',
    name: 'Agent Skills (스킬)',
    kind: '스킬',
    platform: 'Claude Code',
    category: '생산성',
    maturity: '공식',
    summary: '특정 작업 절차·도구를 SKILL.md로 정의해 필요할 때만 로드하는 모델 확장 능력.',
    whatItDoes: [
      '도메인 절차를 SKILL.md로 캡슐화',
      '관련 작업에서 자동 트리거',
      '토큰 효율적으로 전문 지식 주입',
    ],
    install: '.claude/skills/<name>/SKILL.md 작성',
    usage: '관련 요청 시 자동 로드 또는 /<skill> 호출',
    koreanNote: '사내 배포/검증 절차, 디자인 컨벤션을 스킬로 만들면 반복 지시가 줄어듭니다.',
    url: 'https://docs.claude.com/en/docs/claude-code/skills',
    sourceIds: ['claude-code-docs'],
    tags: ['skill', 'claude-code', '절차'],
  },
  {
    id: 'ext-cc-subagent-review',
    name: '코드 리뷰 서브에이전트',
    kind: '서브에이전트',
    platform: 'Claude Code',
    category: '코드 리뷰',
    maturity: '공식',
    summary: '독립 컨텍스트에서 변경분을 리뷰하는 전용 서브에이전트로 메인 작업과 분리.',
    whatItDoes: [
      'git diff 기준 스타일·버그 점검',
      '별도 컨텍스트로 메인 토큰 절약',
      'PR 전 자체 리뷰 루프',
    ],
    install: '.claude/agents/<name>.md에 system prompt + tools 정의',
    usage: '작업 후 서브에이전트로 리뷰 위임',
    koreanNote: '적대적 리뷰(refute) 패턴과 결합하면 거짓 양성을 걸러내기 좋습니다.',
    url: 'https://docs.claude.com/en/docs/claude-code/sub-agents',
    sourceIds: ['claude-code-docs'],
    tags: ['subagent', 'review', 'PR'],
  },
  {
    id: 'ext-cc-slash-commands',
    name: '커스텀 슬래시 명령',
    kind: '슬래시 명령',
    platform: 'Claude Code',
    category: '생산성',
    maturity: '공식',
    summary: '자주 쓰는 프롬프트·절차를 /command로 저장해 반복 작업을 한 번에 호출.',
    whatItDoes: [
      '프롬프트 템플릿을 명령으로 저장',
      '인자($ARGUMENTS) 지원',
      '프로젝트/사용자 스코프 분리',
    ],
    install: '.claude/commands/<name>.md 작성',
    usage: '/<name> 인자 입력',
    koreanNote: '배포·릴리스 체크리스트를 명령으로 만들면 휴먼 에러가 줄어듭니다.',
    url: 'https://docs.claude.com/en/docs/claude-code/slash-commands',
    sourceIds: ['claude-code-docs'],
    tags: ['slash', 'command', '템플릿'],
  },
  {
    id: 'ext-mcp-playwright',
    name: 'Playwright MCP',
    kind: 'MCP 서버',
    platform: '범용',
    category: '브라우저 자동화',
    maturity: '공식',
    summary: '에이전트가 실제 브라우저를 제어해 클릭·입력·스크린샷·접근성 스냅샷을 수행하는 MCP.',
    whatItDoes: [
      '실DOM 탐색·폼 입력·스크린샷',
      'E2E 검증/시각 회귀 보조',
      '접근성 스냅샷으로 액션 결정',
    ],
    install: 'claude mcp add 또는 클라이언트 설정에 서버 등록',
    usage: 'navigate/click/snapshot 도구 호출',
    koreanNote: 'UI 변경을 실제로 띄워 확인하는 검증 루프에 적합합니다.',
    url: 'https://github.com/microsoft/playwright-mcp',
    sourceIds: ['claude-code-docs'],
    tags: ['mcp', 'browser', 'playwright', 'e2e'],
  },
  {
    id: 'ext-mcp-chrome-devtools',
    name: 'Chrome DevTools MCP',
    kind: 'MCP 서버',
    platform: '범용',
    category: '테스트/품질',
    maturity: '공식',
    summary: 'Lighthouse 감사·퍼포먼스 트레이스·네트워크 로그를 에이전트가 직접 수집하는 MCP.',
    whatItDoes: [
      'Lighthouse 데스크톱/모바일 감사',
      '성능 트레이스·인사이트 분석',
      '콘솔/네트워크 로그 수집',
    ],
    install: '클라이언트 MCP 설정에 chrome-devtools 서버 등록',
    usage: 'lighthouse_audit/performance_trace 호출',
    koreanNote: '데스크톱·모바일을 모두 감사해 한국 사용자 체감 성능을 점검하세요.',
    url: 'https://github.com/ChromeDevTools/chrome-devtools-mcp',
    sourceIds: ['claude-code-docs'],
    tags: ['mcp', 'lighthouse', '성능', 'audit'],
  },
  {
    id: 'ext-mcp-github',
    name: 'GitHub MCP',
    kind: 'MCP 서버',
    platform: '범용',
    category: 'Git/PR',
    maturity: '공식',
    summary: '이슈·PR·리뷰·코드 검색을 에이전트가 GitHub API로 직접 다루는 MCP 서버.',
    whatItDoes: ['PR 생성/리뷰/머지, 이슈 관리', '코드/커밋 검색', '릴리스·태그 조회'],
    install: '원격 MCP 등록 + GitHub 토큰 헤더 인증',
    usage: 'create_pull_request/issue_write 등 호출',
    koreanNote: 'DCR 미지원이라 순수 OAuth가 막히면 gh 토큰 헤더로 등록하세요.',
    url: 'https://github.com/github/github-mcp-server',
    sourceIds: ['github-copilot-docs'],
    tags: ['mcp', 'github', 'PR', 'issue'],
  },
  {
    id: 'ext-mcp-postgres',
    name: 'Postgres/DB MCP',
    kind: 'MCP 서버',
    platform: '범용',
    category: '데이터베이스',
    maturity: '커뮤니티',
    summary: '스키마 탐색·쿼리 실행·마이그레이션 점검을 에이전트가 안전하게 수행하는 DB MCP.',
    whatItDoes: ['테이블/스키마 조회', '읽기 쿼리·분석 실행', '마이그레이션 비교/튜닝 보조'],
    install: 'env 게이트된 연결 문자열로 MCP 서버 등록',
    usage: 'execute_query/describe_table 호출',
    koreanNote: '연결 문자열은 env로 주입하고 쓰기 권한은 분리하세요.',
    url: 'https://github.com/modelcontextprotocol/servers',
    sourceIds: ['claude-code-docs'],
    tags: ['mcp', 'postgres', 'database', 'sql'],
  },
  {
    id: 'ext-mcp-context7',
    name: 'Context7 MCP',
    kind: 'MCP 서버',
    platform: '범용',
    category: '검색/리서치',
    maturity: '커뮤니티',
    summary: '라이브러리/프레임워크 최신 공식 문서를 에이전트가 실시간으로 가져오는 문서 MCP.',
    whatItDoes: ['버전별 API 문서 조회', '마이그레이션 가이드 검색', '훈련 데이터 이후 변경 보완'],
    install: 'MCP 설정에 context7 서버 등록',
    usage: 'resolve-library-id → query-docs',
    koreanNote: '최신 버전 API 변경을 기억에 의존하지 않고 확인할 때 유용합니다.',
    url: 'https://github.com/upstash/context7',
    sourceIds: ['claude-code-docs'],
    tags: ['mcp', 'docs', 'research', 'context7'],
  },
  {
    id: 'ext-coderabbit',
    name: 'CodeRabbit PR 리뷰',
    kind: '워크플로우',
    platform: '범용',
    category: '코드 리뷰',
    maturity: '공식',
    summary: 'PR마다 자동 AI 리뷰 코멘트를 달아 머지 게이트로 활용하는 리뷰 워크플로우.',
    whatItDoes: ['PR diff 자동 리뷰·요약', '인라인 제안/보안 점검', '리뷰 게이트로 머지 통제'],
    install: 'GitHub App 설치 후 레포 연동',
    usage: '@coderabbitai review 트리거 / 자동 실행',
    koreanNote: '게이트가 교착(소진)되면 owner --admin bypass 정책을 미리 정해두세요.',
    url: 'https://www.coderabbit.ai/',
    sourceIds: ['coderabbit-pricing'],
    tags: ['review', 'PR', 'gate', 'coderabbit'],
  },
  {
    id: 'ext-cursor-rules',
    name: 'Cursor Rules (.cursor/rules)',
    kind: '룰셋/지침',
    platform: 'Cursor',
    category: '컨텍스트 관리',
    maturity: '공식',
    summary: '프로젝트 규칙·컨벤션을 규칙 파일로 정의해 Cursor가 항상 따르도록 하는 룰셋.',
    whatItDoes: ['코딩 컨벤션/금지 패턴 명문화', '경로별 규칙 스코프', '에이전트 일탈 감소'],
    install: '.cursor/rules/*.mdc 작성',
    usage: '규칙 파일에 globs + 지침 기술',
    koreanNote: '한국어로 규칙을 적어도 동작하며, 팀 컨벤션 공유에 효과적입니다.',
    url: 'https://docs.cursor.com/context/rules',
    sourceIds: ['cursor-docs'],
    tags: ['cursor', 'rules', 'convention', 'context'],
  },
  {
    id: 'ext-cursor-agent',
    name: 'Cursor Agent / Background Agents',
    kind: '워크플로우',
    platform: 'Cursor',
    category: '생산성',
    maturity: '공식',
    summary: '멀티파일 변경을 자율 수행하고 백그라운드로 작업을 위임하는 Cursor 에이전트.',
    whatItDoes: ['자율 멀티파일 편집/실행', '백그라운드 작업 위임', '터미널·테스트 통합'],
    install: 'Cursor 최신 버전 사용',
    usage: 'Agent 패널에서 작업 지시',
    koreanNote: '학생은 Cursor for Students로 Pro를 1년 무료로 쓸 수 있습니다.',
    url: 'https://cursor.com/docs',
    sourceIds: ['cursor-docs'],
    tags: ['cursor', 'agent', 'background'],
  },
  {
    id: 'ext-copilot-custom-instructions',
    name: 'Copilot 커스텀 인스트럭션',
    kind: '룰셋/지침',
    platform: 'GitHub Copilot',
    category: '컨텍스트 관리',
    maturity: '공식',
    summary: '레포의 .github/copilot-instructions.md로 Copilot 응답에 항상 적용할 지침을 정의.',
    whatItDoes: ['레포 전역 응답 지침 주입', '기술 스택/스타일 고정', '반복 설명 제거'],
    install: '.github/copilot-instructions.md 작성',
    usage: '자동 적용',
    koreanNote: '한국어 응답을 원하면 지침에 명시하세요.',
    url: 'https://docs.github.com/en/copilot/customizing-copilot',
    sourceIds: ['github-copilot-docs', 'github-copilot-docs-ko'],
    tags: ['copilot', 'instructions', 'context'],
  },
  {
    id: 'ext-copilot-coding-agent',
    name: 'Copilot Coding Agent',
    kind: '워크플로우',
    platform: 'GitHub Copilot',
    category: 'Git/PR',
    maturity: '공식',
    summary: '이슈를 할당하면 브랜치를 만들고 PR을 올리는 클라우드 코딩 에이전트.',
    whatItDoes: ['이슈 → 브랜치 → PR 자동화', 'CI 통과까지 반복', '리뷰어 지정 협업'],
    install: 'GitHub Copilot 구독에서 활성화',
    usage: '이슈를 Copilot에 할당',
    koreanNote: '무료 등급/학생 팩으로 Copilot 기능 진입이 가능합니다.',
    url: 'https://docs.github.com/en/copilot',
    sourceIds: ['github-copilot-docs', 'github-copilot-plans'],
    tags: ['copilot', 'agent', 'PR', 'cloud'],
  },
  {
    id: 'ext-codex-agents-md',
    name: 'Codex AGENTS.md',
    kind: '룰셋/지침',
    platform: 'Codex CLI',
    category: '컨텍스트 관리',
    maturity: '공식',
    summary: 'AGENTS.md로 Codex/OpenAI 에이전트에 프로젝트 규칙·명령을 전달하는 표준 지침 파일.',
    whatItDoes: ['빌드/테스트 명령 명시', '코딩 규칙·금지사항 정의', '에이전트 일관성 확보'],
    install: '레포 루트에 AGENTS.md 작성',
    usage: '자동 로드',
    koreanNote: 'Claude의 CLAUDE.md와 병행해 멀티 에이전트 환경을 정렬할 수 있습니다.',
    url: 'https://github.com/openai/codex',
    sourceIds: ['openai-codex-cli'],
    tags: ['codex', 'agents-md', 'context'],
  },
  {
    id: 'ext-gemini-cli-extensions',
    name: 'Gemini CLI 확장/도구',
    kind: '플러그인',
    platform: 'Gemini CLI',
    category: '생산성',
    maturity: '공식',
    summary: 'Gemini CLI에 MCP 서버·커스텀 도구를 연결해 워크플로우를 확장.',
    whatItDoes: ['MCP 도구 연결', '커스텀 명령 추가', '오픈소스 기반 확장'],
    install: 'Gemini CLI 설치 후 설정에서 도구 등록',
    usage: 'CLI 내 도구 호출',
    koreanNote: '한국어 안내가 늘고 있어 진입 장벽이 낮습니다.',
    url: 'https://github.com/google-gemini/gemini-cli',
    sourceIds: ['gemini-cli-github'],
    tags: ['gemini', 'cli', 'mcp', 'extension'],
  },
  {
    id: 'ext-cline-mcp',
    name: 'Cline (오픈소스 에이전트)',
    kind: '플러그인',
    platform: '범용',
    category: '생산성',
    maturity: '커뮤니티',
    summary: 'VS Code에서 동작하는 오픈소스 코딩 에이전트로 MCP·다중 모델을 자유롭게 연결.',
    whatItDoes: ['VS Code 통합 자율 편집', '임의 모델/MCP 연결', '오픈소스로 투명한 동작'],
    install: 'VS Code 마켓플레이스에서 Cline 설치',
    usage: '사이드패널에서 작업 지시',
    koreanNote: 'DeepSeek 오프피크 할인 등 저비용 모델과 결합하면 운영비를 낮출 수 있습니다.',
    url: 'https://github.com/cline/cline',
    sourceIds: ['cline-github'],
    tags: ['opensource', 'vscode', 'mcp', 'agent'],
  },
  {
    id: 'ext-agents-sdk-workflow',
    name: 'OpenAI Agents SDK 워크플로우',
    kind: '워크플로우',
    platform: '범용',
    category: '생산성',
    maturity: '공식',
    summary: '도구 호출·핸드오프·가드레일을 갖춘 멀티 에이전트 파이프라인을 코드로 구성.',
    whatItDoes: ['에이전트 간 핸드오프 구성', '가드레일/트레이싱', '도구 호출 오케스트레이션'],
    install: 'openai-agents 패키지 설치',
    usage: 'Agent/Runner로 파이프라인 정의',
    koreanNote: 'Batch API와 결합해 비실시간 파이프라인 비용을 낮추세요.',
    url: 'https://github.com/openai/openai-agents-python',
    sourceIds: ['openai-agents-sdk'],
    tags: ['sdk', 'agents', 'workflow', 'openai'],
  },
  {
    id: 'ext-claude-skill-design',
    name: '디자인 시스템 스킬',
    kind: '스킬',
    platform: 'Claude Code',
    category: '디자인/UI',
    maturity: '커뮤니티',
    summary: '디자인 토큰·컴포넌트 규칙·접근성 기준을 스킬로 묶어 일관된 UI 작업을 유도.',
    whatItDoes: ['토큰/컴포넌트 규약 주입', '접근성·대비 기준 강제', '프로덕트 레지스터 가이드'],
    install: '.claude/skills/<design>/SKILL.md 작성',
    usage: 'UI 작업 시 자동 로드',
    koreanNote: '리빙 스타일가이드(/design) 페이지와 함께 쓰면 컨벤션이 코드와 동기화됩니다.',
    url: 'https://docs.claude.com/en/docs/claude-code/skills',
    sourceIds: ['claude-code-docs'],
    tags: ['skill', 'design', 'a11y', 'ui'],
  },
  {
    id: 'ext-cc-test-runner-hook',
    name: '테스트 자동 실행 워크플로우',
    kind: '워크플로우',
    platform: '범용',
    category: '테스트/품질',
    maturity: '커뮤니티',
    summary: '변경 후 관련 테스트를 자동 실행하고 실패를 에이전트에 되먹여 자가 수선하는 루프.',
    whatItDoes: ['변경 범위 테스트 선택 실행', '실패 로그 자동 피드백', '통과까지 수선 반복'],
    install: 'Stop/PostToolUse 훅 또는 명령으로 테스트 실행 연결',
    usage: 'verify 게이트 명령에 테스트 포함',
    koreanNote: 'pnpm verify처럼 lint+typecheck+test+build를 한 게이트로 묶으면 회귀를 막습니다.',
    url: 'https://docs.claude.com/en/docs/claude-code/hooks',
    sourceIds: ['claude-code-docs'],
    tags: ['test', 'ci', 'self-heal', 'verify'],
  },
  {
    id: 'ext-docs-skill',
    name: '문서 자동 생성 스킬/명령',
    kind: '슬래시 명령',
    platform: '범용',
    category: '문서화',
    maturity: '커뮤니티',
    summary: '코드에서 README·CHANGELOG·API 문서를 일관 포맷으로 생성하는 명령.',
    whatItDoes: ['변경분 기반 문서 갱신', '일관 포맷/한국어 요약', 'PR에 문서 동기화'],
    install: '.claude/commands/docs.md 또는 스킬로 작성',
    usage: '/docs 호출',
    koreanNote: '한국어 사용자 대상 문서는 명령 템플릿에 한글 출력 규칙을 명시하세요.',
    url: 'https://docs.claude.com/en/docs/claude-code/slash-commands',
    sourceIds: ['claude-code-docs'],
    tags: ['docs', 'readme', 'changelog', 'command'],
  },
  {
    id: 'ext-codex-plugin-bundle',
    name: 'Codex 플러그인 번들',
    kind: '플러그인',
    platform: 'Codex CLI',
    category: '생산성',
    maturity: '공식',
    summary:
      'skills, hooks, MCP 서버, ChatGPT 앱을 `.codex-plugin/plugin.json`으로 묶어 설치 가능한 번들로 배포하는 방식.',
    whatItDoes: [
      '스킬·훅·MCP·앱을 단일 플러그인으로 패키징',
      '개인 마켓플레이스/팀 배포 흐름 지원',
      'manifest interface로 설치 화면 메타데이터 구성',
    ],
    install: '.codex-plugin/plugin.json 작성 후 plugin-creator/마켓플레이스 흐름으로 설치',
    usage: '플러그인 활성화 후 포함된 skills/hooks/mcpServers/apps 자동 노출',
    koreanNote:
      '팀 표준 스킬과 MCP를 따로 설명하지 말고 플러그인 하나로 배포할 때 가장 효율적입니다.',
    rank: 1,
    rankReason: 'Codex 생태계 확장의 최상위 패키징 단위이며 스킬·훅·MCP를 함께 묶을 수 있습니다.',
    installDifficulty: '보통',
    installSteps: [
      '.codex-plugin/plugin.json에 name, version, description, interface 작성',
      'skills/, hooks/, .mcp.json, .app.json 중 필요한 구성 추가',
      '로컬 설치 후 포함 capability가 노출되는지 확인',
    ],
    bestFor: ['팀 표준 워크플로', 'MCP 묶음 배포', '스킬·훅 재사용'],
    adoptionSignal: 'OpenAI Codex 공식 플러그인 문서 기준 확장 권장 구조.',
    lastVerified: '2026-06-19',
    thumbnailDomain: 'openai.com',
    thumbnailFit: 'contain',
    url: 'https://developers.openai.com/codex/plugins/build',
    sourceIds: ['openai-codex-plugins', 'openai-codex-plugin-build'],
    tags: ['codex', 'plugin', 'skills', 'hooks', 'mcp', 'marketplace'],
  },
  {
    id: 'ext-claude-official-plugin-marketplace',
    name: 'Claude Code 공식 플러그인 마켓플레이스',
    kind: '플러그인',
    platform: 'Claude Code',
    category: '생산성',
    maturity: '공식',
    summary:
      'Anthropic 공식 플러그인 마켓플레이스에서 LSP, 보안 가이드, PR 리뷰, 외부 도구 MCP 묶음을 설치하는 경로.',
    whatItDoes: [
      '공식/커뮤니티 플러그인 마켓플레이스 연결',
      'LSP·MCP·명령·에이전트 묶음 설치',
      '설치 후 /reload-plugins로 세션 반영',
    ],
    install: '/plugin install github@claude-plugins-official',
    usage: '/plugin 메뉴에서 검색·설치 후 /reload-plugins',
    koreanNote: '처음 시작할 때는 공식 마켓플레이스만 쓰고, 커뮤니티는 신뢰한 repo만 추가하세요.',
    rank: 2,
    rankReason: '설치 UX가 가장 단순하고 공식 마켓플레이스에 실무형 플러그인이 모여 있습니다.',
    installDifficulty: '쉬움',
    installSteps: [
      'Claude Code에서 /plugin 입력',
      'github@claude-plugins-official 설치',
      '필요 플러그인 선택 후 /reload-plugins 실행',
    ],
    bestFor: ['Claude Code 온보딩', '공식 LSP/MCP 번들', '보안·리뷰 플러그인'],
    adoptionSignal: 'Anthropic 문서가 공식 마켓플레이스와 커뮤니티 마켓플레이스 설치 명령을 제공.',
    lastVerified: '2026-06-19',
    thumbnailDomain: 'claude.com',
    thumbnailFit: 'contain',
    url: 'https://code.claude.com/docs/en/discover-plugins',
    sourceIds: ['claude-code-plugin-marketplace', 'claude-code-plugin-create'],
    tags: ['claude-code', 'plugin', 'marketplace', 'official', 'lsp', 'mcp'],
  },
  {
    id: 'ext-openai-apps-sdk-widgets',
    name: 'OpenAI Apps SDK ChatGPT 위젯',
    kind: '위젯',
    platform: '범용',
    category: '에이전트 UI',
    maturity: '공식',
    summary:
      'ChatGPT 안에서 파일 업로드, 다운로드, 모달, 전체화면, MCP 도구 결과 UI를 제공하는 Apps SDK 위젯 표면.',
    whatItDoes: [
      'window.openai 브리지로 파일/모달/표시 모드 제어',
      'MCP tool 결과를 HTML 위젯으로 렌더링',
      'CSP와 widgetDomain으로 임베드 보안 설정',
    ],
    install: 'Apps SDK 프로젝트에서 widget resource와 MCP tool descriptor 등록',
    usage: 'tool 결과의 _meta/openai output template로 ChatGPT UI에 표시',
    koreanNote: '한국어 업무 앱을 ChatGPT 안에서 바로 쓰게 만들 때 가장 공식적인 위젯 경로입니다.',
    rank: 3,
    rankReason: 'ChatGPT 내 배포 표면을 직접 제공해 외부 웹앱보다 전환 비용이 낮습니다.',
    installDifficulty: '고급',
    installSteps: [
      'Apps SDK MCP 서버를 구성하고 tool descriptor 작성',
      'HTML widget resource와 _meta.ui.csp를 등록',
      'ChatGPT에서 파일/모달/표시 모드 동작을 테스트',
    ],
    bestFor: ['ChatGPT 내 업무 위젯', '파일 기반 도구 UI', 'MCP tool 결과 화면'],
    adoptionSignal: 'OpenAI Developers 공식 Apps SDK와 ChatGPT UI component 문서 제공.',
    lastVerified: '2026-06-19',
    thumbnailDomain: 'openai.com',
    thumbnailFit: 'contain',
    url: 'https://developers.openai.com/apps-sdk/build/chatgpt-ui',
    sourceIds: ['openai-apps-sdk', 'openai-apps-sdk-chatgpt-ui'],
    tags: ['openai', 'apps-sdk', 'chatgpt', 'widget', 'mcp', 'ui'],
  },
  {
    id: 'ext-copilotkit-agent-ui',
    name: 'CopilotKit 에이전트 UI',
    kind: '위젯',
    platform: '범용',
    category: '에이전트 UI',
    maturity: '커뮤니티',
    summary:
      'React 앱에 채팅, 사이드바, 팝업, generative UI, shared state, HITL 플로를 얹는 에이전트 UX 프레임워크.',
    whatItDoes: [
      'CopilotChat, CopilotSidebar, CopilotPopup UI 제공',
      'LangGraph, CrewAI, LlamaIndex 등 AG-UI backend 연결',
      '앱 상태를 에이전트와 공유',
    ],
    install: 'React 앱에 @copilotkit/react-core와 @copilotkit/react-ui 추가',
    usage: 'CopilotKit provider와 CopilotChat/Sidebar/Popup 컴포넌트 배치',
    koreanNote: '기존 SaaS 화면에 에이전트 사이드패널을 붙일 때 구현 시간이 짧습니다.',
    rank: 4,
    rankReason: '프론트엔드 앱에 바로 붙는 agentic UX 컴포넌트가 풍부합니다.',
    installDifficulty: '보통',
    installSteps: [
      '프론트엔드 패키지 설치',
      'CopilotKit provider를 앱 루트에 연결',
      '백엔드를 AG-UI 호환 런타임으로 연결',
    ],
    bestFor: ['SaaS 내 AI 사이드바', 'Human-in-the-loop', 'LangGraph UI'],
    adoptionSignal: '공식 문서가 주요 에이전트 백엔드와 UI primitive를 함께 안내.',
    lastVerified: '2026-06-19',
    thumbnailDomain: 'copilotkit.ai',
    thumbnailFit: 'contain',
    url: 'https://docs.copilotkit.ai/',
    sourceIds: ['copilotkit-docs'],
    tags: ['copilotkit', 'agent-ui', 'react', 'chat', 'ag-ui'],
  },
  {
    id: 'ext-assistant-ui-chat',
    name: 'assistant-ui React 챗 위젯',
    kind: '위젯',
    platform: '범용',
    category: '에이전트 UI',
    maturity: '커뮤니티',
    summary:
      'React 기반 AI 채팅 인터페이스, runtime integration, generative UI, 도구 호출 표시를 빠르게 구성하는 UI 스택.',
    whatItDoes: [
      '프리빌트 채팅 UI와 상태 관리 제공',
      'LangGraph/MCP/cloud 템플릿으로 시작',
      '도구 호출·첨부·스트리밍 UX 구성',
    ],
    install: 'npx assistant-ui@latest create',
    usage: '템플릿 선택 후 runtime provider와 Thread UI 연결',
    koreanNote:
      '채팅 UI를 처음부터 만들기보다 템플릿에서 시작해 도메인별 메시지 컴포넌트만 바꾸는 편이 빠릅니다.',
    rank: 5,
    rankReason: '채팅 위젯 자체에 집중한 React 템플릿과 런타임 통합이 강합니다.',
    installDifficulty: '쉬움',
    installSteps: [
      'npx assistant-ui@latest create 실행',
      'minimal, cloud, langgraph, mcp 템플릿 중 선택',
      '모델 runtime과 메시지 컴포넌트 연결',
    ],
    bestFor: ['AI 채팅 UI', 'MCP 챗 템플릿', '도구 호출 표시'],
    adoptionSignal: '공식 문서가 CLI, DevTools, generative UI, agent skills를 안내.',
    lastVerified: '2026-06-19',
    thumbnailDomain: 'assistant-ui.com',
    thumbnailFit: 'contain',
    url: 'https://www.assistant-ui.com/docs',
    sourceIds: ['assistant-ui-docs'],
    tags: ['assistant-ui', 'react', 'chat', 'mcp', 'generative-ui'],
  },
  {
    id: 'ext-ai-elements-shadcn',
    name: 'Vercel AI Elements',
    kind: '위젯',
    platform: '범용',
    category: '에이전트 UI',
    maturity: '공식',
    summary:
      'shadcn/ui 기반 AI 컴포넌트 레지스트리로 대화, 코드, 음성, workflow UI를 프로젝트에 복사해 쓰는 방식.',
    whatItDoes: [
      '대화/코드/음성/워크플로 컴포넌트 제공',
      '프로젝트에 소스 형태로 추가해 커스터마이즈',
      'AI SDK와 shadcn/ui 패턴에 맞춤',
    ],
    install: 'npx ai-elements@latest add conversation',
    usage: '필요 컴포넌트를 registry에서 add 후 앱 상태와 연결',
    koreanNote:
      'shadcn 기반 프로젝트라면 디자인 시스템과 충돌이 적어 운영 UI에 맞게 손보기 쉽습니다.',
    rank: 6,
    rankReason: '컴포넌트를 소스 코드로 가져와 브랜드 UI에 맞추기 쉽습니다.',
    installDifficulty: '쉬움',
    installSteps: [
      'shadcn/ui 프로젝트 준비',
      'npx ai-elements@latest add <component> 실행',
      'AI SDK 스트리밍 상태와 연결',
    ],
    bestFor: ['shadcn 기반 챗봇', '코드 블록 UI', '음성/워크플로 컴포넌트'],
    adoptionSignal: 'Vercel AI SDK 생태계의 공식 AI-native component registry.',
    lastVerified: '2026-06-19',
    thumbnailDomain: 'vercel.com',
    thumbnailFit: 'contain',
    url: 'https://elements.ai-sdk.dev/',
    sourceIds: ['vercel-ai-elements', 'vercel-ai-sdk'],
    tags: ['vercel', 'ai-elements', 'shadcn', 'react', 'chatbot'],
  },
  {
    id: 'ext-gemini-cli-mcp-extensions',
    name: 'Gemini CLI MCP 확장',
    kind: 'MCP 서버',
    platform: 'Gemini CLI',
    category: '생산성',
    maturity: '공식',
    summary:
      'Gemini CLI의 settings.json에 MCP 서버를 등록해 로컬/원격 도구와 리소스를 CLI 대화에 연결하는 확장 방식.',
    whatItDoes: [
      'stdio, SSE, Streamable HTTP MCP 서버 연결',
      '/mcp 명령으로 연결 상태 확인',
      '파일·검색·외부 API 도구를 Gemini CLI에 노출',
    ],
    install: 'settings.json의 mcpServers에 서버 transport와 command/url 등록',
    usage: 'Gemini CLI에서 /mcp로 도구 확인 후 자연어로 호출',
    koreanNote: 'Antigravity CLI 전환 안내가 있는 문서는 날짜와 계정 유형을 함께 확인하세요.',
    rank: 7,
    rankReason: 'Gemini CLI 확장성의 핵심이며 MCP 표준 도구를 재사용할 수 있습니다.',
    installDifficulty: '보통',
    installSteps: [
      'Gemini CLI 설치',
      'settings.json에 mcpServers 블록 추가',
      '/mcp로 서버와 도구 목록 확인',
    ],
    bestFor: ['Gemini CLI 도구 확장', 'MCP 재사용', '로컬 리소스 연결'],
    adoptionSignal: 'Gemini CLI 문서가 MCP transport와 설정 예시를 제공.',
    lastVerified: '2026-06-19',
    thumbnailDomain: 'gemini.google',
    thumbnailFit: 'contain',
    url: 'https://geminicli.com/docs/tools/mcp-server/',
    sourceIds: ['gemini-cli-github', 'gemini-cli-mcp'],
    tags: ['gemini', 'cli', 'mcp', 'extensions', 'tools'],
  },
  {
    id: 'ext-inspect-ai-harness',
    name: 'Inspect AI 평가 하네스',
    kind: '하네스',
    platform: '범용',
    category: '평가/하네스',
    maturity: '공식',
    summary:
      'UK AISI/Meridian이 제공하는 frontier AI eval 프레임워크로 데이터셋, 도구, scorer, sandbox, Inspect View를 갖춘 평가 하네스.',
    whatItDoes: [
      'datasets, solvers, tools, scorers 기반 eval 작성',
      'Inspect View 웹 UI로 결과 탐색',
      'Claude Code, Codex CLI, Gemini CLI 등 외부 에이전트 평가',
    ],
    install: 'pip install inspect-ai',
    usage: 'inspect eval simpleqa.py --model openai/gpt-5 && inspect view',
    koreanNote: '제품 출시 전 회귀 평가와 정책/보안 검증을 CI 게이트로 만들 때 적합합니다.',
    rank: 8,
    rankReason:
      '공식 문서와 웹 뷰, sandbox, 외부 에이전트 연동까지 갖춘 범용 평가 프레임워크입니다.',
    installDifficulty: '보통',
    installSteps: [
      'Python 환경에서 pip install inspect-ai',
      'eval 파일에 dataset/solver/scorer 정의',
      'inspect eval 실행 후 inspect view로 결과 확인',
    ],
    bestFor: ['LLM 평가 CI', '에이전트 도구 평가', '보안/정책 검증'],
    adoptionSignal: 'UK AI Security Institute 기반 오픈소스 평가 프레임워크.',
    lastVerified: '2026-06-19',
    thumbnailDomain: 'inspect.aisi.org.uk',
    thumbnailFit: 'contain',
    url: 'https://inspect.aisi.org.uk/',
    sourceIds: ['inspect-ai-docs'],
    tags: ['inspect', 'eval', 'harness', 'aisi', 'sandbox'],
  },
  {
    id: 'ext-mini-swe-agent-harness',
    name: 'mini-SWE-agent',
    kind: '하네스',
    platform: '범용',
    category: '평가/하네스',
    maturity: '커뮤니티',
    summary:
      'SWE-bench류 소프트웨어 엔지니어링 태스크를 가볍게 실행하는 100줄대 에이전트 하네스와 CLI.',
    whatItDoes: [
      'SWE-bench/로컬 이슈 해결 에이전트 실행',
      'LiteLLM/OpenRouter/Portkey로 다양한 모델 연결',
      'Docker/Podman/Singularity 등 격리 환경 지원',
    ],
    install: 'uv tool install mini-swe-agent 또는 pip install mini-swe-agent',
    usage: 'mini 또는 mini-extra로 태스크 실행',
    koreanNote:
      '큰 SWE-agent보다 먼저 mini 버전으로 설치와 모델 연결을 검증하는 흐름이 현실적입니다.',
    rank: 9,
    rankReason:
      '소프트웨어 에이전트 하네스를 빠르게 체험하고 SWE-bench류 실험으로 확장하기 좋습니다.',
    installDifficulty: '보통',
    installSteps: [
      'uv tool install mini-swe-agent 실행',
      'API 키 또는 LiteLLM 모델 라우팅 설정',
      'mini 명령으로 로컬 repo/benchmark 태스크 실행',
    ],
    bestFor: ['SWE-bench 실험', '코딩 에이전트 비교', '로컬 repo 버그 수정 평가'],
    adoptionSignal: 'mini-SWE-agent v2 문서가 SWE-agent의 기본 선택지로 mini를 안내.',
    lastVerified: '2026-06-19',
    thumbnailDomain: 'mini-swe-agent.com',
    thumbnailFit: 'contain',
    url: 'https://mini-swe-agent.com/latest/quickstart/',
    sourceIds: ['mini-swe-agent-docs', 'mini-swe-agent-quickstart'],
    tags: ['swe-agent', 'swe-bench', 'agent', 'harness', 'liteLLM'],
  },
  {
    id: 'ext-lm-eval-harness',
    name: 'EleutherAI LM Evaluation Harness',
    kind: '하네스',
    platform: '범용',
    category: '평가/하네스',
    maturity: '커뮤니티',
    summary:
      '수십 개 표준 학술 벤치마크와 HF/vLLM/API 백엔드를 지원하는 대표적인 언어 모델 평가 하네스.',
    whatItDoes: [
      'MMLU, HellaSwag 등 표준 task 평가',
      'hf, vllm, api optional backend 지원',
      'GGUF/HF local model과 API 모델 비교',
    ],
    install: 'pip install "lm_eval[hf,vllm,api]"',
    usage: 'lm-eval run --model hf --tasks hellaswag 또는 lm-eval ls tasks',
    koreanNote:
      '로컬 오픈소스 모델을 상용 API와 같은 스크립트로 비교할 때 기준선으로 쓰기 좋습니다.',
    rank: 10,
    rankReason: '오픈 LLM 리더보드 계열과 논문 재현에서 널리 쓰이는 평가 표준입니다.',
    installDifficulty: '보통',
    installSteps: [
      '필요 backend extra를 골라 설치',
      'lm-eval ls tasks로 평가 task 확인',
      '모델 backend별 model_args를 고정해 실행',
    ],
    bestFor: ['학술 벤치마크', 'HF/vLLM/API 비교', 'GGUF 모델 평가'],
    adoptionSignal: 'GitHub README가 Open LLM Leaderboard backend와 폭넓은 사용 사례를 명시.',
    lastVerified: '2026-06-19',
    thumbnailDomain: 'github.com',
    thumbnailFit: 'contain',
    url: 'https://github.com/EleutherAI/lm-evaluation-harness',
    sourceIds: ['lm-eval-harness-github'],
    tags: ['lm-eval', 'benchmark', 'harness', 'hf', 'vllm'],
  },
  {
    id: 'ext-terminal-bench-cli',
    name: 'Terminal-Bench CLI',
    kind: '하네스',
    platform: '범용',
    category: '평가/하네스',
    maturity: '커뮤니티',
    summary:
      '터미널 환경에서 에이전트가 개발/운영 태스크를 수행하는 능력을 측정하는 benchmark CLI.',
    whatItDoes: [
      'Docker 기반 터미널 태스크 실행',
      'terminal-bench/tb CLI로 run, tasks, datasets 관리',
      '자체 에이전트 제출과 private task set 구성',
    ],
    install: 'git, Docker 설치 후 uv tool install terminal-bench',
    usage: 'tb run 또는 terminal-bench --help',
    koreanNote: 'CLI 코딩 에이전트가 실제 셸에서 얼마나 안전하게 일하는지 비교할 때 유용합니다.',
    rank: 11,
    rankReason: '터미널 조작형 에이전트 평가에 특화된 공개 benchmark/CLI입니다.',
    installDifficulty: '보통',
    installSteps: [
      'git과 Docker 설치',
      'uv tool install terminal-bench 실행',
      'tb --help와 tb run으로 smoke test',
    ],
    bestFor: ['터미널 에이전트 평가', 'DevOps 태스크', '에이전트 리더보드 제출'],
    adoptionSignal: '공식 설치 문서가 CLI와 Docker prerequisite를 안내.',
    lastVerified: '2026-06-19',
    thumbnailDomain: 'tbench.ai',
    thumbnailFit: 'contain',
    url: 'https://www.tbench.ai/docs/installation',
    sourceIds: ['terminal-bench', 'terminal-bench-install'],
    tags: ['terminal-bench', 'terminal', 'agent', 'docker', 'benchmark'],
  },
  {
    id: 'ext-opencompass-harness',
    name: 'OpenCompass',
    kind: '하네스',
    platform: '범용',
    category: '평가/하네스',
    maturity: '커뮤니티',
    summary:
      'LLM/VLM 벤치마크, dataset preparation, vLLM/LMDeploy backend, API 모델 테스트를 지원하는 범용 평가 플랫폼.',
    whatItDoes: [
      '다국어·코딩·수학·주관식 평가 구성',
      'vLLM/LMDeploy backend와 API 모델 지원',
      '데이터셋 다운로드와 결과 지속화 가이드 제공',
    ],
    install: 'pip install -U opencompass 또는 pip install "opencompass[full]"',
    usage: 'opencompass config로 모델/데이터셋 지정 후 평가 실행',
    koreanNote: '중국어/다국어 모델 비교와 Qwen 계열 평가를 함께 볼 때 유용합니다.',
    rank: 12,
    rankReason: '데이터셋과 backend 폭이 넓고 아시아권 오픈모델 평가에 강합니다.',
    installDifficulty: '보통',
    installSteps: [
      'Python 3.10/conda 환경 준비',
      'pip install -U opencompass 실행',
      '필요하면 opencompass[api], [vllm], [full] extra 설치',
    ],
    bestFor: ['다국어 모델 평가', 'Qwen/InternLM 계열', 'vLLM backend 평가'],
    adoptionSignal: 'OpenCompass 공식 설치 문서와 leaderboard 생태계 제공.',
    lastVerified: '2026-06-19',
    thumbnailDomain: 'opencompass.org.cn',
    thumbnailFit: 'contain',
    url: 'https://opencompass.readthedocs.io/en/latest/get_started/installation.html',
    sourceIds: ['opencompass-install'],
    tags: ['opencompass', 'benchmark', 'llm', 'vlm', 'vllm'],
  },
  {
    id: 'ext-browsergym-harness',
    name: 'BrowserGym',
    kind: '하네스',
    platform: '범용',
    category: '브라우저 자동화',
    maturity: '커뮤니티',
    summary:
      '웹 태스크 자동화 에이전트를 gym 환경으로 평가하기 위한 브라우저 기반 실험 프레임워크.',
    whatItDoes: [
      '브라우저 조작 task를 Gym 환경으로 구성',
      '웹 에이전트 policy/LLM wrapper 실험',
      'WebArena류 브라우징 평가 기반 제공',
    ],
    install: 'GitHub README 기준 browsergym 패키지/extra 설치',
    usage: 'BrowserGym environment를 생성해 에이전트 loop에서 step 실행',
    koreanNote: '브라우저 조작형 업무 자동화 모델을 비교할 때 Playwright MCP와 함께 보면 좋습니다.',
    rank: 13,
    rankReason: '웹 자동화 에이전트 평가를 실험 환경으로 다루는 대표 오픈소스입니다.',
    installDifficulty: '고급',
    installSteps: [
      'BrowserGym 저장소 README의 package extra 확인',
      '브라우저 의존성과 task dataset 준비',
      'agent loop와 environment step을 연결',
    ],
    bestFor: ['웹 에이전트 연구', '브라우저 자동화 평가', 'WebArena류 실험'],
    adoptionSignal: 'ServiceNow BrowserGym GitHub 저장소 공개.',
    lastVerified: '2026-06-19',
    thumbnailDomain: 'github.com',
    thumbnailFit: 'contain',
    url: 'https://github.com/ServiceNow/BrowserGym',
    sourceIds: ['browsergym-github'],
    tags: ['browsergym', 'browser', 'webarena', 'agent', 'gym'],
  },
  {
    id: 'ext-helm-harness',
    name: 'Stanford CRFM HELM',
    kind: '하네스',
    platform: '범용',
    category: '평가/하네스',
    maturity: '커뮤니티',
    summary:
      'Holistic Evaluation of Language Models 계열 평가 프레임워크로 모델, 시나리오, metric, leaderboard 재현을 지원.',
    whatItDoes: [
      '언어 모델 holistic benchmark 실행',
      '모델/시나리오/토크나이저 확장',
      'HEIM/VHELM 등 multimodal 확장 문서 제공',
    ],
    install: 'Python 3.10 가상환경에서 pip install crfm-helm',
    usage: 'helm-run, run entries configuration으로 평가 실행',
    koreanNote: '학술/정책형 비교표를 만들 때 단일 점수보다 metric별 tradeoff를 보여주기 좋습니다.',
    rank: 14,
    rankReason: 'HELM 리더보드와 논문 재현 관점의 신뢰도가 높습니다.',
    installDifficulty: '보통',
    installSteps: [
      'Python 3.10 virtualenv 또는 conda 환경 생성',
      'pip install crfm-helm 실행',
      'credentials와 run entries 설정 후 평가',
    ],
    bestFor: ['학술 비교', '다중 metric 평가', 'leaderboard 재현'],
    adoptionSignal: 'Stanford CRFM HELM 공식 설치 문서 제공.',
    lastVerified: '2026-06-19',
    thumbnailDomain: 'crfm.stanford.edu',
    thumbnailFit: 'contain',
    url: 'https://crfm-helm.readthedocs.io/en/latest/installation/',
    sourceIds: ['helm-install'],
    tags: ['helm', 'crfm', 'benchmark', 'evaluation', 'stanford'],
  },
  {
    id: 'ext-promptfoo-eval-redteam',
    name: 'Promptfoo 평가/레드팀 하네스',
    kind: '하네스',
    platform: '범용',
    category: '평가/하네스',
    maturity: '공식',
    summary:
      'LLM 앱의 prompt, model, RAG 품질을 matrix로 평가하고 red-teaming/CI/CD 게이트까지 연결하는 오픈소스 CLI/라이브러리.',
    whatItDoes: [
      'prompt/model/RAG benchmark를 선언형 config로 실행',
      'LLM 보안 취약점과 jailbreak 리스크 red team report 생성',
      'CLI, 라이브러리, CI/CD workflow로 회귀 테스트 자동화',
    ],
    install: 'npm install -g promptfoo 또는 npx promptfoo@latest',
    usage: 'promptfoo init 후 config에 provider/test를 정의하고 promptfoo eval 실행',
    koreanNote:
      '출시 전 prompt 회귀 테스트와 보안 점검을 한 번에 묶고 싶을 때 가장 실무적인 첫 선택입니다.',
    rank: 15,
    rankReason: '평가와 red-teaming, 보고서, CI/CD까지 한 도구에서 처리하는 범용성이 큽니다.',
    installDifficulty: '쉬움',
    installSteps: [
      'npm, npx, Homebrew 중 하나로 promptfoo 설치',
      'promptfoo --version으로 설치 확인',
      'promptfoo init 후 provider, prompt, test matrix 작성',
      'promptfoo eval을 CI 또는 릴리스 게이트에 연결',
    ],
    bestFor: ['prompt 회귀 테스트', 'LLM red teaming', 'RAG 품질 점검', 'CI/CD 평가 게이트'],
    adoptionSignal: '공식 문서가 2026-06-19 기준 OpenAI 소속 전환과 로컬/프라이빗 실행을 안내.',
    lastVerified: '2026-06-19',
    thumbnailDomain: 'promptfoo.dev',
    thumbnailFit: 'contain',
    url: 'https://www.promptfoo.dev/docs/intro/',
    sourceIds: ['promptfoo-intro', 'promptfoo-install'],
    tags: [
      'promptfoo',
      'promptfoo red teaming',
      'red teaming',
      'evaluation',
      'RAG',
      'CI/CD',
      'OpenAI',
    ],
  },
  {
    id: 'ext-ragas-rag-agent-evals',
    name: 'Ragas RAG/Agent 평가',
    kind: '하네스',
    platform: '범용',
    category: '평가/하네스',
    maturity: '커뮤니티',
    summary:
      'RAG와 agent workflow를 context precision/recall, faithfulness, tool call accuracy 같은 metric으로 반복 개선하는 평가 프레임워크.',
    whatItDoes: [
      'RAG retrieval/context/answer 품질 metric 제공',
      'tool call accuracy, tool call F1, agent goal accuracy 등 agent metric 제공',
      'dataset, experiment, result tracking과 LangChain/LlamaIndex 통합 지원',
    ],
    install: 'pip install ragas',
    usage: 'Python에서 evaluate()로 dataset과 metric을 지정하거나 CLI RAG evaluation 예제 실행',
    koreanNote:
      '사내 문서 RAG가 그럴듯하게만 보일 때, 검색과 답변 품질을 metric별로 쪼개 확인하기 좋습니다.',
    rank: 16,
    rankReason:
      'RAG와 tool-using agent 품질을 일반 benchmark보다 업무 단위 metric에 가깝게 볼 수 있습니다.',
    installDifficulty: '보통',
    installSteps: [
      'pip install ragas로 설치',
      '평가 dataset과 ground truth 또는 reference answer 준비',
      'faithfulness, context recall, tool call accuracy 등 metric 선택',
      'evaluate() 결과를 experiment 단위로 저장하고 prompt/RAG 설정을 비교',
    ],
    bestFor: [
      'RAG faithfulness',
      'retrieval precision/recall',
      'tool call accuracy',
      'agent goal accuracy',
    ],
    adoptionSignal:
      '공식 문서가 RAG, prompt, AI workflow, AI agent 평가 튜토리얼과 metric catalog를 제공.',
    lastVerified: '2026-06-19',
    thumbnailDomain: 'docs.ragas.io',
    thumbnailFit: 'contain',
    url: 'https://docs.ragas.io/en/stable/',
    sourceIds: ['ragas-docs', 'ragas-install'],
    tags: [
      'ragas',
      'Ragas tool call accuracy',
      'RAG',
      'faithfulness',
      'context recall',
      'tool call accuracy',
      'agent eval',
    ],
  },
  {
    id: 'ext-langsmith-evaluations',
    name: 'LangSmith Evaluations',
    kind: '하네스',
    platform: '범용',
    category: '평가/하네스',
    maturity: '공식',
    summary:
      'LangSmith의 dataset, target function, evaluator, trace를 묶어 agent/RAG/chatbot을 offline·online 평가하는 운영형 평가 표면.',
    whatItDoes: [
      'dataset, target function, evaluator로 regression/unit/backtest 평가 실행',
      'production trace와 feedback을 online evaluation/monitoring으로 연결',
      'workspace-level evaluator와 OpenEvals 기반 LLM-as-judge 확장',
    ],
    install: 'pip install -U langsmith openevals openai',
    usage: 'client.evaluate(target, data=..., evaluators=[...]) 실행 후 LangSmith UI에서 비교',
    koreanNote:
      'LangChain/LangGraph 기반 서비스라면 tracing과 평가를 같은 화면에서 묶어 운영 품질을 추적할 수 있습니다.',
    rank: 17,
    rankReason: '프로덕션 관측성과 offline/online 평가 루프를 연결하는 상용 운영성이 강합니다.',
    installDifficulty: '보통',
    installSteps: [
      'LangSmith 계정과 LANGSMITH_API_KEY 준비',
      'langsmith, openevals, openai 패키지 설치',
      'dataset, target function, evaluator를 정의',
      'client.evaluate 실행 후 UI에서 experiment를 비교',
    ],
    bestFor: [
      'production agent QA',
      'offline evaluation',
      'online evaluation',
      'LLM-as-judge',
      'trace 기반 회귀 테스트',
    ],
    adoptionSignal:
      'LangSmith 공식 문서가 lifecycle 전반의 offline/online evaluation과 workspace evaluator를 안내.',
    lastVerified: '2026-06-19',
    thumbnailDomain: 'smith.langchain.com',
    thumbnailFit: 'contain',
    url: 'https://docs.langchain.com/langsmith/evaluation-concepts',
    sourceIds: [
      'langsmith-docs',
      'langsmith-evaluation-concepts',
      'langsmith-evaluation-quickstart',
      'langsmith-evaluators',
    ],
    tags: [
      'LangSmith',
      'LangSmith online evaluation',
      'OpenEvals',
      'offline eval',
      'online eval',
      'LLM-as-judge',
      'trajectory',
    ],
  },
  {
    id: 'ext-ollama-local-runtime',
    name: 'Ollama 로컬 모델 런타임',
    kind: '모델 런타임',
    platform: '범용',
    category: '로컬 모델',
    maturity: '공식',
    summary:
      'Kimi, GLM, DeepSeek, Qwen, Gemma 등 오픈 모델을 로컬 CLI/API로 실행하고 IDE·에이전트 도구와 연결하는 런타임.',
    whatItDoes: [
      'ollama run으로 모델 다운로드/실행',
      'localhost:11434 REST API와 Python/JS client 제공',
      'Open WebUI, LibreChat, Continue, Codex 등과 통합',
    ],
    install: 'macOS/Linux: curl -fsSL https://ollama.com/install.sh | sh',
    usage: 'ollama run <model> 또는 localhost:11434 API 호출',
    koreanNote:
      '처음 로컬 LLM을 켤 때 가장 진입 장벽이 낮고, 이후 Open WebUI를 붙이면 팀 공유가 쉬워집니다.',
    rank: 18,
    rankReason: '로컬 모델 실행의 설치 난이도가 낮고 통합 생태계가 큽니다.',
    installDifficulty: '쉬움',
    installSteps: [
      'OS별 설치 스크립트 또는 Docker image 실행',
      'ollama run gemma4 같은 작은 모델로 smoke test',
      '필요하면 Open WebUI/IDE extension과 localhost API 연결',
    ],
    bestFor: ['로컬 모델 입문', '오프라인 챗봇', 'IDE/에이전트 로컬 모델 연결'],
    adoptionSignal: 'GitHub README가 170k+ stars, REST API, Python/JS client, 통합 목록을 제공.',
    lastVerified: '2026-06-19',
    thumbnailDomain: 'ollama.com',
    thumbnailFit: 'contain',
    url: 'https://github.com/ollama/ollama',
    sourceIds: ['ollama-github'],
    tags: ['ollama', 'local-llm', 'runtime', 'open-source', 'api'],
  },
  {
    id: 'ext-open-webui-local-frontend',
    name: 'Open WebUI',
    kind: '로컬 모델 UI',
    platform: '범용',
    category: '로컬 모델',
    maturity: '커뮤니티',
    summary:
      'Ollama/OpenAI 호환 backend를 웹 UI로 감싸는 self-hosted LLM 프런트엔드와 확장 가능한 채팅 인터페이스.',
    whatItDoes: [
      'Docker로 로컬 웹 UI 실행',
      'Ollama, OpenAI compatible backend 연결',
      '모델/사용자/프롬프트/확장 관리',
    ],
    install:
      'docker run -d -p 3000:8080 -v open-webui:/app/backend/data ghcr.io/open-webui/open-webui:main',
    usage: 'http://localhost:3000 접속 후 모델 backend 연결',
    koreanNote:
      '가족/팀 내부망용 로컬 챗봇은 Ollama 단독보다 Open WebUI를 붙이는 편이 운영하기 쉽습니다.',
    rank: 19,
    rankReason: '로컬 모델을 비개발자도 쓰게 만드는 대표 self-hosted 웹 UI입니다.',
    installDifficulty: '쉬움',
    installSteps: [
      'Docker image pull 또는 docker run 실행',
      '브라우저에서 localhost:3000 접속',
      'Ollama base URL 또는 OpenAI-compatible endpoint 설정',
    ],
    bestFor: ['로컬 챗 UI', 'Ollama 프런트엔드', '사내 self-hosted LLM'],
    adoptionSignal: '공식 quick start가 Docker, CUDA, Ollama bundled image를 안내.',
    lastVerified: '2026-06-19',
    thumbnailDomain: 'openwebui.com',
    thumbnailFit: 'contain',
    url: 'https://docs.openwebui.com/getting-started/quick-start/',
    sourceIds: ['open-webui-quickstart'],
    tags: ['open-webui', 'ollama', 'docker', 'local-ui', 'self-hosted'],
  },
  {
    id: 'ext-vllm-serving',
    name: 'vLLM 서빙 런타임',
    kind: '모델 런타임',
    platform: '범용',
    category: '모델 서빙',
    maturity: '커뮤니티',
    summary: '대형 오픈 모델을 OpenAI 호환 endpoint로 고성능 서빙하는 inference/serving 엔진.',
    whatItDoes: [
      'vllm serve로 OpenAI compatible API 제공',
      'Tensor parallel, paged attention 기반 고처리량 서빙',
      'GLM/Qwen/Mistral 등 HF 모델 배포',
    ],
    install: 'pip install vllm',
    usage: 'vllm serve zai-org/GLM-5.1',
    koreanNote: '로컬 PC보다 GPU 서버에서 여러 사용자가 쓰는 API endpoint를 만들 때 적합합니다.',
    rank: 20,
    rankReason: '오픈 모델을 API 서비스로 배포하는 기본 선택지 중 하나입니다.',
    installDifficulty: '고급',
    installSteps: [
      'CUDA/Python 환경과 GPU 메모리 확인',
      'pip install vllm 실행',
      'vllm serve <model>로 OpenAI 호환 endpoint 노출',
    ],
    bestFor: ['GPU 서버 서빙', 'OpenAI 호환 API', 'GLM/Qwen 대형 모델'],
    adoptionSignal: 'GLM-5.1 모델 카드가 vLLM serve 예시를 제공.',
    lastVerified: '2026-06-19',
    thumbnailDomain: 'docs.vllm.ai',
    thumbnailFit: 'contain',
    url: 'https://docs.vllm.ai/en/latest/getting_started/installation/',
    sourceIds: ['vllm-install', 'zai-glm51-hf'],
    tags: ['vllm', 'serving', 'openai-compatible', 'glm', 'gpu'],
  },
  {
    id: 'ext-sglang-serving',
    name: 'SGLang 서빙 런타임',
    kind: '모델 런타임',
    platform: '범용',
    category: '모델 서빙',
    maturity: '커뮤니티',
    summary:
      'Llama, Qwen, DeepSeek, Kimi, GLM, Mistral 등 대형 모델의 structured generation과 고성능 serving을 지원하는 프레임워크.',
    whatItDoes: [
      'OpenAI-compatible server 제공',
      'structured output, tool/agent workload 최적화',
      'NVIDIA/AMD/TPU 등 다양한 하드웨어 지원',
    ],
    install: 'pip install sglang',
    usage:
      'python3 -m sglang.launch_server --model-path zai-org/GLM-5.1 --host 0.0.0.0 --port 30000',
    koreanNote: 'GLM/Kimi/DeepSeek 계열 대형 모델을 서빙할 때 vLLM과 함께 비교할 가치가 큽니다.',
    rank: 21,
    rankReason: 'GLM-5.1 모델 카드가 공식 실행 경로로 안내하며 최신 대형 모델 지원 폭이 넓습니다.',
    installDifficulty: '고급',
    installSteps: [
      'GPU/CUDA 또는 Docker 환경 준비',
      'pip install sglang 실행',
      'launch_server로 모델 endpoint를 띄우고 curl로 테스트',
    ],
    bestFor: ['GLM/Kimi/DeepSeek 서빙', 'structured generation', '대형 모델 inference'],
    adoptionSignal: 'SGLang GitHub README가 GLM/Kimi/DeepSeek/Qwen 등 폭넓은 모델 지원을 명시.',
    lastVerified: '2026-06-19',
    thumbnailDomain: 'sglang.ai',
    thumbnailFit: 'contain',
    url: 'https://github.com/sgl-project/sglang',
    sourceIds: ['sglang-github', 'zai-glm51-hf'],
    tags: ['sglang', 'serving', 'glm', 'deepseek', 'kimi', 'structured-generation'],
  },
  {
    id: 'ext-glm51-local-stack',
    name: 'GLM-5.1 로컬/서빙 스택',
    kind: '모델 런타임',
    platform: '범용',
    category: '모델 서빙',
    maturity: '공식',
    summary:
      'MIT 라이선스 GLM-5.1을 Transformers, vLLM, SGLang, Docker Model Runner, GGUF/Ollama/LM Studio 계열로 실행하는 설치 경로.',
    whatItDoes: [
      'HF model card 기반 GLM-5.1 실행',
      'vLLM/SGLang OpenAI 호환 endpoint 구성',
      'Docker Model Runner와 GGUF quantization 경로 비교',
    ],
    install:
      'vllm serve "zai-org/GLM-5.1" 또는 python3 -m sglang.launch_server --model-path "zai-org/GLM-5.1"',
    usage: 'OpenAI 호환 /v1/chat/completions endpoint로 GLM 호출',
    koreanNote:
      '754B급 모델은 로컬 노트북용이 아니라 서버/클라우드 GPU, 양자화 변형, 프록시 비용까지 같이 검토하세요.',
    rank: 22,
    rankReason: '설치형 오픈소스 모델 비교에서 최신 GLM 계열의 대표 실행 경로입니다.',
    installDifficulty: '고급',
    installSteps: [
      'Hugging Face 모델 카드에서 라이선스와 권장 런타임 확인',
      'vLLM 또는 SGLang으로 OpenAI compatible endpoint 실행',
      '작은 quantized 변형은 Ollama/LM Studio/GGUF 경로를 별도 검토',
    ],
    bestFor: ['GLM 오픈웨이트 평가', '코딩/에이전트 모델 비교', '자체 호스팅 PoC'],
    adoptionSignal: 'Hugging Face model card가 vLLM, SGLang, Docker Model Runner 실행 예시를 제공.',
    lastVerified: '2026-06-19',
    thumbnailDomain: 'z.ai',
    thumbnailFit: 'contain',
    url: 'https://huggingface.co/zai-org/GLM-5.1',
    sourceIds: ['zai-glm51-hf', 'zai-glm51-docs', 'vllm-install', 'sglang-github'],
    tags: ['glm', 'zai', 'zhipu', 'open-weight', 'vllm', 'sglang', 'docker-model-runner'],
  },
  {
    id: 'ext-llama-cpp-runtime',
    name: 'llama.cpp / GGUF 런타임',
    kind: '모델 런타임',
    platform: '범용',
    category: '로컬 모델',
    maturity: '커뮤니티',
    summary:
      'GGUF quantized 모델을 CPU, Metal, CUDA, Vulkan 등 다양한 backend에서 실행하는 경량 C/C++ 런타임.',
    whatItDoes: [
      'GGUF 모델 로컬 추론',
      'CLI와 OpenAI-compatible server 제공',
      'CPU/Apple Silicon/다양한 GPU backend 지원',
    ],
    install: 'GitHub README 기준 cmake 빌드 또는 prebuilt binary 사용',
    usage: 'llama-server -m model.gguf 또는 llama-cli -m model.gguf',
    koreanNote: '노트북/맥에서 작은 양자화 모델을 비교할 때 Ollama보다 세밀한 튜닝이 가능합니다.',
    rank: 23,
    rankReason: '대부분의 로컬 모델 UI/런타임이 의존하거나 호환하는 핵심 GGUF 생태계입니다.',
    installDifficulty: '고급',
    installSteps: [
      'GGUF 모델 파일 확보',
      'llama.cpp를 빌드하거나 release binary 사용',
      'llama-server 또는 llama-cli로 smoke test',
    ],
    bestFor: ['GGUF 모델', 'CPU/Apple Silicon 실험', '최소 의존성 로컬 추론'],
    adoptionSignal: 'GitHub 저장소가 100k+ stars 규모의 대표 로컬 LLM 런타임.',
    lastVerified: '2026-06-19',
    thumbnailDomain: 'github.com',
    thumbnailFit: 'contain',
    url: 'https://github.com/ggml-org/llama.cpp',
    sourceIds: ['llama-cpp-github'],
    tags: ['llama.cpp', 'gguf', 'local-llm', 'cpu', 'metal', 'cuda'],
  },
  {
    id: 'ext-hf-tgi-serving',
    name: 'Hugging Face TGI',
    kind: '모델 런타임',
    platform: '범용',
    category: '모델 서빙',
    maturity: '공식',
    summary:
      'Hugging Face Text Generation Inference로 오픈 모델을 Docker/소스 빌드 기반 production endpoint로 서빙.',
    whatItDoes: [
      'Docker 기반 text-generation server 실행',
      'HF Hub 모델 배포와 streaming inference',
      'GPU 서버 production serving에 초점',
    ],
    install: 'Docker 권장 또는 TGI repo clone 후 make install',
    usage: 'text-generation-launcher 또는 Docker image로 endpoint 실행',
    koreanNote:
      'HF Hub 중심 운영이면 TGI, OpenAI 호환 API 중심 운영이면 vLLM/SGLang을 함께 비교하세요.',
    rank: 24,
    rankReason: 'Hugging Face 생태계와 production serving 문서가 잘 정리되어 있습니다.',
    installDifficulty: '고급',
    installSteps: [
      'Docker 기반 quick start 확인',
      '필요 모델과 GPU 메모리 산정',
      'endpoint health와 streaming 응답 확인',
    ],
    bestFor: ['HF Hub 모델 배포', 'production endpoint', 'streaming inference'],
    adoptionSignal: 'Hugging Face 공식 TGI 설치 문서가 Docker를 권장.',
    lastVerified: '2026-06-19',
    thumbnailDomain: 'huggingface.co',
    thumbnailFit: 'contain',
    url: 'https://huggingface.co/docs/text-generation-inference/en/installation',
    sourceIds: ['hf-tgi-install'],
    tags: ['huggingface', 'tgi', 'serving', 'docker', 'inference'],
  },
  {
    id: 'ext-docker-model-runner',
    name: 'Docker Model Runner',
    kind: '모델 런타임',
    platform: '범용',
    category: '로컬 모델',
    maturity: '공식',
    summary:
      'Docker 환경에서 모델을 pull/run하고 REST API, Open WebUI, IDE/agent integration으로 연결하는 Docker AI 모델 실행 표면.',
    whatItDoes: [
      'docker model run으로 모델 실행',
      'Docker Model Runner REST API 제공',
      'Open WebUI와 agent/IDE integration 안내',
    ],
    install: 'Docker Desktop/Engine의 Model Runner 기능 활성화 후 docker model run <model>',
    usage: 'docker model run hf.co/zai-org/GLM-5.1',
    koreanNote:
      '이미 Docker 기반 개발/배포를 쓰는 팀은 로컬 모델 실행도 같은 운영 감각으로 관리할 수 있습니다.',
    rank: 25,
    rankReason: 'Docker 사용자에게 가장 익숙한 설치형 모델 실행 UX를 제공합니다.',
    installDifficulty: '보통',
    installSteps: [
      'Docker Model Runner 문서 기준 기능 활성화',
      'docker model run으로 작은 모델 실행',
      'REST API 또는 Open WebUI integration 테스트',
    ],
    bestFor: ['Docker 중심 팀', '로컬 모델 REST API', 'Open WebUI 연결'],
    adoptionSignal: 'Docker 공식 AI Model Runner 문서와 GLM-5.1 model card 실행 예시 제공.',
    lastVerified: '2026-06-19',
    thumbnailDomain: 'docker.com',
    thumbnailFit: 'contain',
    url: 'https://docs.docker.com/ai/model-runner/',
    sourceIds: ['docker-model-runner', 'zai-glm51-hf'],
    tags: ['docker', 'model-runner', 'local-llm', 'glm', 'open-webui'],
  },
  {
    id: 'ext-anythingllm-local-workspace',
    name: 'AnythingLLM Self-hosted',
    kind: '로컬 모델 UI',
    platform: '범용',
    category: '로컬 모델',
    maturity: '커뮤니티',
    summary:
      '로컬/클라우드 LLM, vector DB, agent skills, embedded chat widget을 갖춘 self-hosted AI workspace.',
    whatItDoes: [
      'Docker로 localhost:3001 workspace 실행',
      'Ollama, LM Studio, cloud LLM provider 연결',
      '문서 RAG, agent skills, embedded widget 제공',
    ],
    install: 'docker pull mintplexlabs/anythingllm:latest 후 persistent volume으로 컨테이너 실행',
    usage: 'http://localhost:3001 접속 후 LLM/vector DB 설정',
    koreanNote:
      '문서 기반 사내 지식 챗봇과 embedded widget을 한 번에 보고 싶을 때 Open WebUI와 비교하세요.',
    rank: 26,
    rankReason: '챗 UI를 넘어 workspace/RAG/agent skill까지 한 화면에서 운영합니다.',
    installDifficulty: '보통',
    installSteps: [
      'docker pull mintplexlabs/anythingllm:latest',
      'storage volume을 반드시 마운트해 컨테이너 실행',
      'localhost:3001에서 LLM과 vector DB 연결',
    ],
    bestFor: ['RAG workspace', 'embedded chat widget', '로컬/클라우드 혼합 LLM'],
    adoptionSignal: '공식 Docker 문서가 persistent storage와 localhost 접속을 안내.',
    lastVerified: '2026-06-19',
    thumbnailDomain: 'anythingllm.com',
    thumbnailFit: 'contain',
    url: 'https://docs.anythingllm.com/installation-docker/local-docker',
    sourceIds: ['anythingllm-docker'],
    tags: ['anythingllm', 'rag', 'local-ui', 'docker', 'workspace', 'widget'],
  },
  {
    id: 'ext-lm-studio-local-ui',
    name: 'LM Studio',
    kind: '로컬 모델 UI',
    platform: '범용',
    category: '로컬 모델',
    maturity: '공식',
    summary:
      '데스크톱 앱에서 모델 검색·다운로드·채팅·로컬 서버 실행을 제공하는 설치형 로컬 LLM 프런트엔드.',
    whatItDoes: [
      '데스크톱 GUI로 모델 다운로드/실행',
      'OpenAI compatible local server 제공',
      'GPU offload와 로컬 채팅 설정 조정',
    ],
    install: 'LM Studio 앱 설치 후 모델 검색/다운로드',
    usage: '앱에서 모델 로드 후 Chat 또는 Local Server 실행',
    koreanNote:
      '터미널보다 GUI가 필요한 사용자에게 추천하고, 팀용 웹 UI는 Open WebUI/AnythingLLM과 비교하세요.',
    rank: 27,
    rankReason: '비개발자가 설치형 오픈 모델을 GUI로 체험하기 좋습니다.',
    installDifficulty: '쉬움',
    installSteps: [
      'OS별 LM Studio 앱 설치',
      '모델 카탈로그에서 작은 instruct 모델 다운로드',
      'Chat 또는 Local Server로 응답 확인',
    ],
    bestFor: ['데스크톱 로컬 챗', '비개발자 오픈모델 체험', 'OpenAI compatible local server'],
    adoptionSignal: 'LM Studio 공식 문서가 앱과 개발자 사용면을 제공.',
    lastVerified: '2026-06-19',
    thumbnailDomain: 'lmstudio.ai',
    thumbnailFit: 'contain',
    url: 'https://lmstudio.ai/docs',
    sourceIds: ['lmstudio-docs'],
    tags: ['lm-studio', 'desktop', 'local-ui', 'openai-compatible', 'gguf'],
  },
  {
    id: 'ext-openhands-agent-canvas',
    name: 'OpenHands Agent Canvas',
    kind: '하네스',
    platform: '범용',
    category: '평가/하네스',
    maturity: '커뮤니티',
    summary:
      '브라우저 기반 agent canvas와 Docker/npm quickstart로 로컬 코딩 에이전트 실험 환경을 구성하는 OpenHands 표면.',
    whatItDoes: [
      '로컬/클라우드 코딩 에이전트 실행',
      'MCP, hooks, plugin형 확장 문서 제공',
      'LLM provider를 바꿔 개발 태스크 실험',
    ],
    install: 'OpenHands quick start 기준 npm 또는 Docker로 Agent Canvas 실행',
    usage: 'Agent Canvas에서 provider 설정 후 repo/태스크 실행',
    koreanNote:
      '오픈소스 코딩 에이전트 UI와 하네스가 필요하면 Cline과 mini-SWE-agent 사이에서 비교하세요.',
    rank: 28,
    rankReason: '로컬 코딩 에이전트 UI와 실행 환경을 함께 제공하는 오픈소스 스택입니다.',
    installDifficulty: '보통',
    installSteps: [
      'Quick Start에서 npm 또는 Docker 설치 경로 선택',
      'Agent Canvas 실행',
      'LLM provider와 workspace 권한 설정',
    ],
    bestFor: ['오픈소스 코딩 에이전트', '로컬 개발 태스크', 'Agent UI 비교'],
    adoptionSignal: 'OpenHands 공식 quick start가 Cloud/Agent Canvas/npm/Docker 경로를 안내.',
    lastVerified: '2026-06-19',
    thumbnailDomain: 'openhands.dev',
    thumbnailFit: 'contain',
    url: 'https://docs.openhands.dev/overview/quickstart',
    sourceIds: ['openhands-docs'],
    tags: ['openhands', 'agent', 'coding', 'docker', 'canvas'],
  },
  {
    id: 'ext-codex-skills',
    name: 'Codex Skills',
    kind: '스킬',
    platform: 'Codex CLI',
    category: '컨텍스트 관리',
    maturity: '공식',
    summary:
      'SKILL.md와 scripts/references/assets를 묶어 Codex가 관련 작업에서만 전문 절차를 로드하게 하는 경량 확장 단위.',
    whatItDoes: [
      'name/description frontmatter로 자동 트리거',
      'scripts, references, assets, agents 폴더로 절차 재사용',
      'config.toml에서 스킬 비활성화 가능',
    ],
    install: 'skills/<name>/SKILL.md 작성 또는 $skill-creator 사용',
    usage: '관련 요청에서 자동 로드하거나 명시적으로 스킬 이름 호출',
    koreanNote: '사내 배포/검증/디자인 규칙을 매번 프롬프트에 붙이지 말고 스킬로 분리하세요.',
    rank: 29,
    rankReason: '반복 지시를 줄이고 토큰 효율적인 전문 절차를 만들 수 있습니다.',
    installDifficulty: '쉬움',
    installSteps: [
      'skills/<name>/SKILL.md에 name과 description 작성',
      '필요 시 scripts/와 references/를 추가',
      '테스트 요청에서 스킬이 선택되는지 확인',
    ],
    bestFor: ['반복 업무 절차', '팀 컨벤션', '전문 도구 사용법'],
    adoptionSignal: 'OpenAI Codex 공식 Skills 문서 제공.',
    lastVerified: '2026-06-19',
    thumbnailDomain: 'openai.com',
    thumbnailFit: 'contain',
    url: 'https://developers.openai.com/codex/skills',
    sourceIds: ['openai-codex-skills'],
    tags: ['codex', 'skills', 'skill.md', 'workflow', 'context'],
  },
  {
    id: 'ext-codex-managed-hooks',
    name: 'Codex Managed Hooks',
    kind: '훅',
    platform: 'Codex CLI',
    category: '테스트/품질',
    maturity: '공식',
    summary:
      'requirements.toml과 config.toml로 PreToolUse/PostToolUse/Stop 훅을 관리해 명령, 검증, 보안 정책을 강제하는 흐름.',
    whatItDoes: [
      'managed hook requirement를 프로젝트에 선언',
      'PreToolUse/PostToolUse/Stop 이벤트에서 명령 실행',
      'allow_managed_hooks_only로 승인된 훅만 허용',
    ],
    install: 'requirements.toml의 [hooks]와 ~/.codex/config.toml features.hooks 설정',
    usage: '파일 편집/도구 호출/응답 종료 시 훅 자동 실행',
    koreanNote: 'verify 게이트, 포맷, 시크릿 스캔을 Codex 작업 루프에 붙이는 핵심 지점입니다.',
    rank: 30,
    rankReason: '에이전트 작업 결과를 자동 검증하는 운영 안전장치입니다.',
    installDifficulty: '고급',
    installSteps: [
      'config.toml에서 features.hooks 활성화',
      'requirements.toml에 managed hook 정의',
      '테스트 repo에서 hook matcher와 timeout 확인',
    ],
    bestFor: ['자동 포맷/검증', '보안 스캔', '팀 정책 강제'],
    adoptionSignal: 'OpenAI Codex Hooks 문서가 managed hooks 설정 예시를 제공.',
    lastVerified: '2026-06-19',
    thumbnailDomain: 'openai.com',
    thumbnailFit: 'contain',
    url: 'https://developers.openai.com/codex/hooks',
    sourceIds: ['openai-codex-hooks'],
    tags: ['codex', 'hooks', 'managed-hooks', 'verify', 'security'],
  },
  {
    id: 'ext-claude-code-lsp-plugins',
    name: 'Claude Code LSP 플러그인',
    kind: '플러그인',
    platform: 'Claude Code',
    category: '테스트/품질',
    maturity: '공식',
    summary:
      'Claude Code 공식 마켓플레이스의 code intelligence/LSP 플러그인으로 symbol, diagnostics, jump-to-definition 맥락을 강화.',
    whatItDoes: [
      '언어 서버 기반 코드 인텔리전스 제공',
      'diagnostics와 symbol 맥락을 에이전트에 연결',
      '대형 repo 탐색 정확도 개선',
    ],
    install: '/plugin install <lsp-plugin>@claude-plugins-official',
    usage: '설치 후 repo 언어 서버가 노출되는지 /plugin 상태 확인',
    koreanNote:
      '대형 TypeScript/Nest/React repo는 LSP 플러그인으로 탐색 오류를 줄이는 효과가 큽니다.',
    rank: 31,
    rankReason: '코딩 에이전트의 repo 이해도를 직접 높이는 실무형 플러그인입니다.',
    installDifficulty: '보통',
    installSteps: [
      '공식 마켓플레이스 설치',
      '대상 언어의 LSP 플러그인 선택',
      '진단/정의 이동이 동작하는지 확인',
    ],
    bestFor: ['대형 repo 탐색', '타입 오류 진단', '언어별 코드 이해'],
    adoptionSignal: 'Claude Code 공식 discovery 문서가 code intelligence LSP plugin 목록을 안내.',
    lastVerified: '2026-06-19',
    thumbnailDomain: 'claude.com',
    thumbnailFit: 'contain',
    url: 'https://code.claude.com/docs/en/discover-plugins',
    sourceIds: ['claude-code-plugin-marketplace'],
    tags: ['claude-code', 'lsp', 'code-intelligence', 'plugin', 'diagnostics'],
  },
  {
    id: 'ext-gemini-cli-skills',
    name: 'Gemini CLI Skills',
    kind: '스킬',
    platform: 'Gemini CLI',
    category: '컨텍스트 관리',
    maturity: '공식',
    summary:
      'Gemini CLI에서 반복 작업 절차와 도메인 지식을 skill로 캡슐화해 프로젝트/사용자 작업 흐름에 재사용하는 방식.',
    whatItDoes: [
      '절차형 지식을 skill로 분리',
      'CLI 작업 맥락에 필요한 지침만 로드',
      'MCP/extension과 조합해 워크플로 구성',
    ],
    install: 'Gemini CLI skills 문서 기준 skill scaffold 작성',
    usage: 'CLI 작업에서 skill을 명시하거나 자동 선택되도록 description 조정',
    koreanNote: 'Codex/Claude와 같은 이름의 스킬을 맞춰두면 멀티 에이전트 팀 운영이 쉬워집니다.',
    rank: 32,
    rankReason: 'Gemini CLI 사용자가 반복 절차를 표준화하는 경량 확장 단위입니다.',
    installDifficulty: '보통',
    installSteps: [
      'Gemini CLI 설치와 설정 확인',
      'skills 문서 기준 skill 정의',
      '실제 작업 요청에서 선택/실행 여부 확인',
    ],
    bestFor: ['Gemini CLI 반복 절차', '팀 컨벤션', '멀티 에이전트 스킬 정렬'],
    adoptionSignal: 'Gemini CLI docs가 skills와 creating skills 문서를 제공.',
    lastVerified: '2026-06-19',
    thumbnailDomain: 'gemini.google',
    thumbnailFit: 'contain',
    url: 'https://geminicli.com/docs/cli/skills/',
    sourceIds: ['gemini-cli-skills', 'gemini-cli-github'],
    tags: ['gemini', 'skills', 'cli', 'workflow', 'context'],
  },
  {
    id: 'ext-litellm-proxy-gateway',
    name: 'LiteLLM Proxy Gateway',
    kind: '워크플로우',
    platform: '범용',
    category: '모델 서빙',
    maturity: '커뮤니티',
    summary:
      'OpenAI 호환 gateway로 OpenAI, Anthropic, Vertex/Gemini, Bedrock, Ollama, vLLM, TGI 등 여러 모델 호출을 하나의 endpoint로 묶는 라우터.',
    whatItDoes: [
      '100개 이상 LLM을 OpenAI Chat Completions 형식으로 라우팅',
      'virtual key, spend tracking, budgets, admin UI, guardrail 구성',
      'retry, fallback, load balancing과 Langfuse/MLflow/Helicone callback 지원',
    ],
    install: "uv tool install 'litellm[proxy]'",
    usage: 'litellm --model openai/gpt-4o 또는 litellm --model ollama/<model-name>',
    koreanNote:
      '여러 모델을 앱마다 따로 붙이지 말고 사내 표준 base URL 하나로 감싸고 싶을 때 검토하세요.',
    rank: 33,
    rankReason:
      '모델 수가 늘어날수록 비용, 키, fallback, 로컬 endpoint 연결을 중앙화하는 가치가 큽니다.',
    installDifficulty: '보통',
    installSteps: [
      "uv tool install 'litellm[proxy]'로 gateway 설치",
      'litellm --model <provider/model>로 로컬 proxy 실행',
      'OpenAI SDK base_url을 http://localhost:4000으로 바꿔 smoke test',
      '운영에서는 config.yaml, virtual key, budget, callback을 별도 설정',
    ],
    bestFor: ['멀티 모델 라우팅', 'OpenAI 호환 gateway', 'fallback/load balancing', '비용 추적'],
    adoptionSignal:
      '공식 문서가 SDK, Proxy Server, virtual keys, cost tracking, guardrails, observability callback을 함께 안내.',
    lastVerified: '2026-06-19',
    thumbnailDomain: 'litellm.ai',
    thumbnailFit: 'contain',
    url: 'https://docs.litellm.ai/docs/proxy/quick_start',
    sourceIds: ['litellm-docs', 'litellm-proxy-quickstart'],
    tags: [
      'LiteLLM',
      'LiteLLM Proxy',
      'model router',
      'OpenAI compatible gateway',
      'fallback',
      'cost tracking',
      'vLLM',
      'Ollama',
    ],
  },
  {
    id: 'ext-openrouter-model-router',
    name: 'OpenRouter 모델 라우터',
    kind: '워크플로우',
    platform: '범용',
    category: '모델 서빙',
    maturity: '공식',
    summary:
      '수백 개 AI 모델을 단일 endpoint와 OpenAI SDK baseURL 호환으로 호출하고, model catalog와 Agent SDK까지 제공하는 모델 라우팅 서비스.',
    whatItDoes: [
      '단일 /api/v1/chat/completions endpoint로 모델 카탈로그 접근',
      '@openrouter/sdk와 @openrouter/agent로 typed SDK/agent loop 구성',
      'OpenAI SDK를 baseURL만 바꿔 drop-in replacement로 사용',
    ],
    install: 'npm install @openrouter/sdk 또는 npm install @openrouter/agent',
    usage: "baseURL: 'https://openrouter.ai/api/v1' + OPENROUTER_API_KEY",
    koreanNote:
      '새 모델 후보를 빠르게 비교할 때 유용하지만, 운영 투입 전 데이터 처리와 fallback 비용 정책을 분리해 확인하세요.',
    rank: 34,
    rankReason:
      '모델 카탈로그 실험 속도가 빠르고 OpenAI SDK 호환성이 좋아 PoC 단계에서 유용합니다.',
    installDifficulty: '쉬움',
    installSteps: [
      'OpenRouter API key 발급',
      '@openrouter/sdk 또는 OpenAI SDK baseURL 방식 선택',
      'model slug와 optional attribution headers 설정',
      'fallback/비용/데이터 정책을 운영 기준으로 검토',
    ],
    bestFor: ['모델 카탈로그 실험', 'OpenAI SDK 호환 호출', 'Agent SDK', '빠른 PoC'],
    adoptionSignal:
      '공식 quickstart가 API, Client SDK, Agent SDK, OpenAI SDK drop-in replacement 경로를 안내.',
    lastVerified: '2026-06-19',
    thumbnailDomain: 'openrouter.ai',
    thumbnailFit: 'contain',
    url: 'https://openrouter.ai/docs/quickstart',
    sourceIds: ['openrouter-quickstart'],
    tags: [
      'OpenRouter',
      'OpenRouter model router',
      'model catalog',
      'OpenAI SDK',
      '@openrouter/sdk',
      '@openrouter/agent',
    ],
  },
  {
    id: 'ext-langfuse-observability-evals',
    name: 'Langfuse Observability/Evals',
    kind: '하네스',
    platform: '범용',
    category: '평가/하네스',
    maturity: '커뮤니티',
    summary:
      'LLM trace, prompt management, dataset/experiment, LLM-as-judge, production trace 평가를 묶는 오픈소스 관측성·평가 플랫폼.',
    whatItDoes: [
      'production/development trace와 prompt version을 추적',
      'LLM-as-judge, code evaluator, user feedback, manual labeling 지원',
      'Docker self-hosting과 Python/JS SDK, LangChain/LlamaIndex/OpenAI 통합 제공',
    ],
    install: 'Langfuse Cloud 사용 또는 Docker Compose/Kubernetes self-hosting 구성',
    usage: 'SDK tracing 후 dataset/experiment/evaluation score를 Langfuse dashboard에서 비교',
    koreanNote: '모델 교체 전후의 비용·품질·사용자 피드백을 한 화면에 남기고 싶은 팀에 맞습니다.',
    rank: 35,
    rankReason:
      '모델 라우터와 하네스 사이에서 실제 운영 trace와 평가 score를 연결하는 핵심 관측성 후보입니다.',
    installDifficulty: '고급',
    installSteps: [
      'Cloud 또는 Docker Compose/Kubernetes self-hosting 경로 선택',
      'SDK 키와 host URL을 앱/라우터에 설정',
      'trace, prompt, score, dataset, experiment를 같은 프로젝트로 묶기',
      '민감 데이터 masking/sampling과 보관 정책 확정',
    ],
    bestFor: ['LLM observability', 'production evals', 'prompt management', 'dataset experiments'],
    adoptionSignal:
      '공식 문서가 open source, Python/JavaScript SDK, OpenAI/LangChain/LlamaIndex 통합과 self-hosting 구조를 안내.',
    lastVerified: '2026-06-19',
    thumbnailDomain: 'langfuse.com',
    thumbnailFit: 'contain',
    url: 'https://langfuse.com/docs',
    sourceIds: ['langfuse-docs', 'langfuse-self-hosting'],
    tags: [
      'Langfuse',
      'Langfuse observability',
      'LLM-as-a-judge',
      'production evals',
      'dataset experiments',
      'prompt management',
    ],
  },
]

export type ExtensionKindFilter = ExtensionKind | 'all'
export type ExtensionPlatformFilter = ExtensionPlatform | 'all'
export type ExtensionCategoryFilter = ExtensionCategory | 'all'

export const extensionKinds: ExtensionKind[] = [
  '플러그인',
  '훅',
  '스킬',
  '슬래시 명령',
  '서브에이전트',
  'MCP 서버',
  '하네스',
  '위젯',
  '로컬 모델 UI',
  '모델 런타임',
  '워크플로우',
  '룰셋/지침',
  '템플릿',
]

export const extensionPlatforms: ExtensionPlatform[] = [
  'Claude Code',
  'Cursor',
  'GitHub Copilot',
  'Codex CLI',
  'Gemini CLI',
  'Windsurf',
  '범용',
]

export const extensionCategories: ExtensionCategory[] = [
  '코드 리뷰',
  '테스트/품질',
  '문서화',
  'Git/PR',
  '보안',
  '디자인/UI',
  '데이터베이스',
  '브라우저 자동화',
  '검색/리서치',
  '생산성',
  '배포/DevOps',
  '컨텍스트 관리',
  '평가/하네스',
  '에이전트 UI',
  '로컬 모델',
  '모델 서빙',
]

export function getExtensionSearchText(extension: AgentExtension): string {
  return [
    extension.name,
    extension.kind,
    extension.platform,
    extension.category,
    extension.maturity,
    extension.summary,
    ...extension.whatItDoes,
    extension.install,
    extension.usage,
    extension.koreanNote ?? '',
    extension.rank?.toString() ?? '',
    extension.rankReason ?? '',
    extension.installDifficulty ?? '',
    extension.adoptionSignal ?? '',
    extension.lastVerified ?? '',
    ...(extension.installSteps ?? []),
    ...(extension.bestFor ?? []),
    ...extension.tags,
  ].join(' ')
}

export function getExtensionStats() {
  return {
    total: agentExtensions.length,
    kinds: new Set(agentExtensions.map((e) => e.kind)).size,
    platforms: new Set(agentExtensions.map((e) => e.platform)).size,
    categories: new Set(agentExtensions.map((e) => e.category)).size,
    official: agentExtensions.filter((e) => e.maturity === '공식').length,
    ranked: agentExtensions.filter((e) => typeof e.rank === 'number').length,
  }
}

export function getExtensionRankGrade(extension: Pick<AgentExtension, 'rank'>): ExtensionRankGrade {
  if (!extension.rank) return '미분류'
  if (extension.rank <= 8) return 'S'
  if (extension.rank <= 18) return 'A'
  if (extension.rank <= 28) return 'B'
  return 'C'
}
